<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OM.Dedi.Core\OM.Dedi.Core.csproj" />
    <ProjectReference Include="..\OM.Dedi.Runtime\OM.Dedi.Runtime.csproj" />
    <ProjectReference Include="..\OM.Dedi.Discord\OM.Dedi.Discord.csproj" />
  </ItemGroup>
</Project>
